# This is a basic workflow to help you get started with Actions

name: Deploy DEV branch to teleconsult-demo-dev-public
env:
  CI: ""

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
      - name: Build project
        run: |
          echo Install dependencies
          npm install
          echo Build to /build
          npm run build
          cp build/index.html build/404.html
          echo "dev.telemed.demo.ekami.ch" > build/CNAME
      - name: Deploy /build to teleconsult-demo-public public repo
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:ekami-ch/teleconsult-demo-dev-public.git
          BRANCH: main
          FOLDER: build
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_DEV_PRIVATE_KEY }}
